---
title: "Ingrid's Draft Sheet"
author: "Ingrid"
date: "4/15/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r libraries}
library(tidyverse)
library(here)
library(brickr)
library(rayshader)
library(rgl)
library(circlepackeR)
library(data.tree)
library(treemap)
```



```{r datasets, echo=FALSE}
sets <- read.csv(here("data/sets.csv"))

colors <- read.csv(here("data/colors (2).csv"))

inventories <- read.csv(here("data/inventories.csv"))

parts_inventory <- read.csv(here("data/inventory_parts.csv"))

sets_inventory <- read.csv(here("data/inventory_sets.csv"))

minifigs <- read.csv(here("data/minifigs.csv"))

parts_categories <- read.csv(here("data/part_categories.csv"))

parts_relationships <- read.csv(here("data/part_relationships.csv"))

parts <- read.csv(here("data/parts.csv"))

themes <- read.csv(here("data/themes.csv"))

minifig_inventory <- read.csv(here("data/inventory_minifigs.csv"))
```

```{r renaming variables}
colors <- rename(colors, "color_id"="id")

parts_categories <- rename(parts_categories, "part_cat_id"="id")

inventories<- rename(inventories, "inventory_id"="id")
```


```{r red brick}
#This is a brick
brick <- data.frame(
  Level="A",
  X1 = rep(3,4), #The number 3 is the brickrID for 'bright red'
  X2 = rep(3,4)
)

brick %>% 
  bricks_from_table() %>% 
  build_bricks()

#Rotate the default view for a better snapshot
rgl::par3d(userMatrix = rgl::rotate3d(rgl::par3d("userMatrix"), 0.75*pi, 0, 0 ,1))
```


```{r milf circlepackR}
#USC Millennium Falcon, 7541 parts, released 2017
#set num = 75192-1

inventories %>%
  filter(set_num == "75192-1")

millenium_falcon <- parts_inventory %>%
  filter(inventory_id == 19670) %>% #inventory ID gotten from previous step
  left_join(colors, by="color_id") %>%
  left_join(parts, by="part_num") %>%
  left_join(parts_categories, by="part_cat_id") %>%
  rename("part_cat"="name", "color_name"="name.x", "part_name"="name.y")


millenium_falcon$pathString <- paste("mf", 
                            millenium_falcon$color_name, 
                            millenium_falcon$part_cat,
                            millenium_falcon$part_name,
                            millenium_falcon$quantity,
                            sep = "/")

MILF <- as.Node(millenium_falcon)

#color, then part category, then part name, then part quantity
m <- circlepackeR(MILF, size = "quantity", width = 1000, height = 800)

m
```

```{r}
#Tree house set, 3037 parts, released 2019
#set num = 21318-1

inventories %>%
  filter(set_num == "21318-1")

treehouse <- parts_inventory %>%
  filter(inventory_id == 37728) %>%
  left_join(colors, by="color_id") %>%
  left_join(parts, by="part_num") %>%
  left_join(parts_categories, by="part_cat_id") %>%
  rename("part_cat"="name", "color_name"="name.x", "part_name"="name.y")

treehouse$pathString <- paste("mf", 
                            treehouse$color_name, 
                            treehouse$part_cat,
                            treehouse$part_name,
                            treehouse$quantity,
                            sep = "/")

TREE <- as.Node(treehouse)

#color, then part category, then part type, 
tree <- circlepackeR(TREE, size = "quantity",  width = 1000, height = 800)

tree
```

```{r 2000 colors treemap}

bigcolors <- sets %>%
  filter(year == 2000) %>%
  left_join(inventories, by="set_num") %>%
  left_join(parts_inventory, by="inventory_id") %>%
  left_join(colors, by="color_id") %>%
  filter(num_parts > 0) %>%
  select(2, 3, 10, 12, 13) %>%
  group_by(name.y) %>%
  summarise(n=sum(quantity)) %>%
  arrange(desc(n)) %>%
  rename("color"="name.y", "n_parts"="n")

treemap(bigcolors,
            index="color",
            vSize="n_parts",
            type="index"
            )

bigcolors %>%
  head(10)
```

```{r}
millennium_figs <- inventories %>%
  filter(inventory_id == 19670) %>%
  left_join(minifig_inventory, by="inventory_id") %>%
  left_join(minifigs, by="fig_num") %>%
  select(4, 6, 7)

millennium_figs
```

