---
title: "Isabelle's draft sheet"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

## libraries

library(tidyverse)
library(readr)
library(brickr)
library(rayshader)
library(rgl)
library(circlepackeR)
library(tidyr)
library(networkD3)
library(ggraph)
library(data.tree)
library(treemap)
library(DiagrammeR)
library(scales)
library(bubbles)
library(RColorBrewer)




```




```{r}
## loading the data 

sets <- read.csv("~/Math241/Iggy-Izzy/data/sets.csv")

colors <- read.csv("~/Math241/Iggy-Izzy/data/colors (2).csv") 

inventories <- read.csv("~/Math241/Iggy-Izzy/data/inventories.csv")

parts_inventory <- read.csv("~/Math241/Iggy-Izzy/data/inventory_parts.csv")

sets_inventory <- read.csv("~/Math241/Iggy-Izzy/data/inventory_sets.csv")

minifigs <- read.csv("~/Math241/Iggy-Izzy/data/minifigs.csv")

parts_categories <- read.csv("~/Math241/Iggy-Izzy/data/part_categories.csv")

parts_relationships <- read.csv("~/Math241/Iggy-Izzy/data/part_relationships.csv")

parts <- read.csv("~/Math241/Iggy-Izzy/data/parts.csv")

themes <- read.csv("~/Math241/Iggy-Izzy/data/themes.csv")





```


```{r, eval= FALSE}

## building mosaics 


demo_img = tempfile() 
download.file("http://ryantimpe.com/files/mf_unicorn.PNG", demo_img, mode="wb")

mosaic1 <- png::readPNG("man.png") %>% 
  image_to_mosaic(img_size = 36) #Length of each side of mosaic in "bricks"

mosaic1 %>% build_mosaic()

mosaic2 <- png::readPNG("manny.png") %>% 
  image_to_mosaic(img_size = 36) 
#Length of each side of mosaic in "bricks"

mosaic2 %>% build_mosaic()


mosaic3 <- png::readPNG("holden.png") %>% 
  image_to_mosaic(img_size = 36) #Length of each side of mosaic in "bricks"

mosaic3 %>% build_mosaic()


```

```{r}
## wranglin 


smallthemes <- themes %>%
  select(id, name) %>%
  rename("theme_id"=id)

## dataset containing sets, themes, and number of parts 

sets_themes <- sets %>%
  filter(num_parts >= 40) %>%
  left_join(smallthemes, by="theme_id") %>%
  rename("set_name"=name.x, "theme_name"=name.y)


#data_edge <- sets_themes$edges
#data_edge$from <- gsub(".*\\.","",data_edge$from)
#data_edge$to <- gsub(".*\\.","",data_edge$to)
#head(data_edge)  

#class(data.edge)


#data_tree <- FromDataFrameNetwork(data_edge)
#data_nested <- ToDataFrameTree(data_tree, 
#                            level1 = function(x) x$path[2],
#                            level2 = function(x) x$path[3],
#                            level3 = function(x) x$path[4],
#                            level4 = function(x) x$path[5])[-1,-1]

#data_nested <- na.omit(data_nested)




```

```{r}


the_themes <- sets_themes %>%
  count(theme_name) %>%
  top_n(5)


#trying to create a nested data frame using data.tree 


sets_themes$pathString <- paste("legos", 
                            sets_themes$theme_name, 
                            sets_themes$set_name, 
                            sets_themes$num_parts,
                            sep = "/")

sets_themes_5 <- left_join(the_themes,sets_themes, by="theme_name")



legos <- as.Node(sets_themes_5) 
print(legos, "year", "num_parts", limit = 10)

```

```{r}

## trying to create dendrograms 
## not working 

plot(legos)

plot(as.dendrogram(legos), center = TRUE)



##plot with networkD3
## radial network messy top 5 themes sooo many sets 

legoslist <- ToListExplicit(legos, unname = TRUE)
radialNetwork(legoslist)



## trying to make a more legiable radial network 

top_set <- sets_themes %>% 
  count(set_name) %>%
  top_n(50)

sets_themes_topsets <- left_join(top_set,sets_themes, by="set_name")


legos2 <- as.Node(sets_themes_topsets) 
print(legos2, "year", "num_parts", limit = 10)

legoslist2 <- ToListExplicit(legos2, unname = TRUE)
radialNetwork(legoslist2)


plot(as.dendrogram(legos2, height = "year"))


## the best radial network 

  # top 10 themes 
top_themes <- sets_themes %>%
  count(theme_name) %>% 
  top_n(10)

more_frigin_legos <- left_join(top_themes,sets_themes, by="theme_name")

# top 10o largest sets by number of parts 

more_frigin_legos <- more_frigin_legos %>%
  top_n(100, num_parts)


legos3 <- as.Node(more_frigin_legos) 
print(legos3, "year", "num_parts", limit = 10)


## within the top 10 themes these are the 100 sets with the most pieces. 
legoslist3 <- ToListExplicit(legos3, unname = TRUE)
radialNetwork(legoslist3)

```


```{r}

#bubbles

lego_df <- ToDataFrameTable(legos2, 
                             className = function(x) x$parent$name, 
                             packageName = "set_name", "num_parts")

bubbles(
  lego_df$num_parts,
  label = lego_df$packageName, 
  substr(lego_df$packageName, 1, 2),
  tooltip = lego_df$packageName,
  color = col_factor(
    brewer.pal(9,"Set1"),
    factor(lego_df$className)
  )(lego_df$className),
  height = 1000,
  width = 1000
)

```


```{r, include = FALSE, eval = FALSE}
# Circlepacker package


sets_themes$pathString <- paste("legos", 
                            sets_themes$theme_name, 
                            sets_themes$set_name, 
                            sets_themes$num_parts,
                            sep = "/")


sets_themes_5 <- left_join(the_themes,sets_themes, by="theme_name") %>% top_n(100, num_parts)

legos <- as.Node(sets_themes_5)
print(legos, "year", "num_parts", limit = 10)


# Make the plot
#circlepackeR(population, size = "value")

# You can custom the minimum and maximum value of the color range.
p <- circlepackeR(legos, size = "num_parts", color_min = "hsl(56,80%,80%)", color_max = "hsl(341,30%,40%)", width = 1000, height = 800)

p


```
